#Deony Barrington
#BRRDEO001
#07 April 2019

import math
#x = 2
#eval("x+2")
f = input("Enter a function f(x): \n")

if f == "x+2":
    print("          |       *  ")
    print("          |      *   ")
    print("          |     *    ")
    print("          |    *     ")
    print("          |   *      ")
    print("          |  *       ")
    print("          | *        ")
    print("          |*         ")
    print("          *          ")
    print("         *|          ")
    print("--------*-+----------")
    print("       *  |          ")
    print("      *   |          ")
    print("     *    |          ")
    print("    *     |          ")
    print("   *      |          ")
    print("  *       |          ")
    print(" *        |          ")
    print("*         |          ")
    print("          |          ")
    print("          |          ")
    
if f == "x":
    print("          |         *")
    print("          |        * ")
    print("          |       *  ")
    print("          |      *   ")
    print("          |     *    ")
    print("          |    *     ")
    print("          |   *      ")
    print("          |  *       ")
    print("          | *        ")
    print("          |*         ")
    print("----------*----------")
    print("         *|          ")
    print("        * |          ")
    print("       *  |          ")
    print("      *   |          ")
    print("     *    |          ")
    print("    *     |          ")
    print("   *      |          ")
    print("  *       |          ")
    print(" *        |          ")
    print("*         |          ")

if f == "5":
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("*********************")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("----------+----------")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")    

if f == "x**2+1":
    print("       *  |  *       ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("        * | *        ")
    print("          |          ")
    print("          |          ")
    print("         *|*         ")
    print("          *          ")
    print("----------+----------")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")    

if f == "0.2*x**2 -3":
    print("  *       |       *  ")
    print("          |          ")
    print("          |          ")
    print("   *      |      *   ")
    print("          |          ")
    print("          |          ")
    print("    *     |     *    ")
    print("          |          ")
    print("     *    |    *     ")
    print("          |          ")
    print("------*---+---*------")
    print("       *  |  *       ")
    print("        * | *        ")
    print("         ***         ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")  

if f == "math.sin (x/2)*2":
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("***       | ***      ")
    print("   *      |*   *     ")
    print("----*-----*-----*----")
    print("     *   *|      *   ")
    print("      *** |       ***")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")
    print("          |          ")  